### ISSUE TITLE
Feature request: seconds on staging/shepherding screens

### ISSUE THREAD

**Issue by prophile** [PeterJCLaw/srcomp-screens#6]
Request from the shepherding teams to use seconds, rather than truncating to minutes, on the staging and shepherding screen. This includes match timings and the wall clock.

**Comment by PeterJCLaw** [comment]
Looks like Moment JS (which we're using) doesn't offer a choice of precision: https://momentjs.com/docs/#/displaying/fromnow/

**Comment by PeterJCLaw** [comment]
However https://www.npmjs.com/package/moment-duration-format exists :tada:
