### ISSUE TITLE
Feature request: match spacing in bottom line on staging screen

### ISSUE THREAD

**Issue by prophile** [PeterJCLaw/srcomp-screens#7]
It would be good for confirmation to give the standard match slot length, game length, and derived match spacing on the bottom of the staging screen to avoid mistakes about how long the slots are.

**Comment by PeterJCLaw** [comment]
> standard match slot length ... and derived match spacing

These are currently (by definition) the same thing.

**Comment by prophile** [comment]
I wasn't sufficiently clear there, being rather sloppy with words. I mean something like

> 4½ min slots, 2½ min games, 2 min gap
