### ISSUE TITLE
Feature request: website link on outside screens

### ISSUE THREAD

**Issue by prophile** [PeterJCLaw/srcomp-screens#8]
We've quite often seen teams photographing the outside screens. The information they're looking to capture is available in a more convenient format at their pits, and live, on the website.

We should consider putting a website URL at the bottom of the outside screens that they can read.

**Comment by PeterJCLaw** [comment]
I wonder if a QR code with the link would help too?

**Comment by prophile** [comment]
Could do. I didn't know whether we could rely on the screen resolution, but if so it would be a good addition.
